# Site settings
title: 
email: lowgrav@icloud.com
description: jason only lighter and crisper
baseurl: "/jason-lite"

twitter_username: mellowgnomebeer
avatar: "https://pbs.twimg.com/profile_images/449655782833782785/OrDnwCQ8.png" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "jason" # Set default author name
      categories: "personal"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
